### ISSUE TITLE
Function parameter help sometimes omits first parameter

### ISSUE THREAD

**Issue by TedDriggs** [saviorisdead/RustyCode#238]
```rust
fn defend_result<'a, A: Adjudicate>(context: &'a ResolverContext<'a>,
                                    resolver: &'a mut ResolverState<'a, A>,
                                    order: &MappedMainOrder<'a>)
                                    -> Option<Defend<'a>> {
    match order.command {
        MainCommand::Move(..) => {
            Some(Defend(support::find_successful_for(context, resolver, order)))
        }
        _ => None,
    }
}
```
![screen shot 2017-01-10 at 2 20 03 pm](https://cloud.githubusercontent.com/assets/4805575/21827308/eefdcd00-d73f-11e6-8747-4469c39a68d6.png)

Notice that the bold section is the second parameter before the generic declaration and that `context` is missing completely.

![screen shot 2017-01-10 at 2 20 12 pm](https://cloud.githubusercontent.com/assets/4805575/21827307/eefba264-d73f-11e6-8ed0-bd74b0180403.png)

Notice that the bold section is now from the generic declaration's comma to the end of the second selection.

**Comment by KalitaAlexey** [comment]
@TedDriggs,
Hi.
Unfortunately this repository is deprecated because the maintainer doesn't respond.
I have made a fork: https://github.com/KalitaAlexey/vscode-rust
Please open an issue in the fork.

Please attach a minimal example reproducing the problem. To do that replace all your types with simple dummies.
