### ISSUE TITLE
invalid urls on Windows

### ISSUE THREAD

**Issue by fuchsnj** [saviorisdead/RustyCode#45]
```
ERROR:racer::core: read_file couldn't open "\"c:\\Users\\nathan\\Documents\\repos\\myapp\\src\\file.rs\"". Returning empty string
thread 'searcher' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 123, message: "The filename, directory name, or volume label syntax is incorrect." } }', ../src/libcore\result.rs:741
stack backtrace:
   0:           0x97d79a - <unknown>
   1:           0x985f6e - <unknown>
   2:           0x940c4c - <unknown>
   3:           0x9413bb - <unknown>
   4:           0x97a582 - <unknown>
   5:           0x9a10d8 - <unknown>
   6:           0x4fac1b - <unknown>
   7:           0x403d6e - <unknown>
   8:           0x96d731 - <unknown>
   9:           0x404b83 - <unknown>
  10:           0x98459d - <unknown>
  11:     0x7ffc2c3a2d91 - <unknown>
```

**Comment by vadimcn** [comment]
It's a Racer bug - phildawes/racer#442

**Comment by Draivin** [comment]
Should probably revert #43 until then.
Or drop racer daemons and spawn a new process on every command.

**Comment by saviorisdead** [comment]
Hmm, ok i'll revert #43 for now, until bug is fixed.

**Comment by vadimcn** [comment]
Racer now has a [tab-delimited interface](https://github.com/phildawes/racer/pull/445) option.  Unfortunately, I hadn't figured out in time to [bump racer's version](https://github.com/phildawes/racer/pull/451) as well, but hopefully this will land soon too.

**Comment by phildawes** [comment]
Hi @vadimcn. I merged the version bump. WRT rusty-code do you need me to release the racer version to crates.io or is git master ok?

**Comment by Draivin** [comment]
@saviorisdead Should we support old racer versions or direct the users to install the latest version?  
It should be really easy now that rust stable has the `cargo install` subcommand, perhaps it should even be included in the README.  
This bug can only be fixed on the old versions by dropping the `racer daemon` command and spawning a new subprocess on every request. The alternative is leaving support for the old version as is, without supporting files with whitespace.

@phildawes I don't believe updating the crate is really needed  since `cargo install` supports git urls and you recommend installing using the git form in your README.

**Comment by saviorisdead** [comment]
@Draivin Yes, I think you are right, we should update readme. I'll take care of that.

**Comment by vadimcn** [comment]
I was thinking of leaving support for old versions as-is.  It worked okay so far, after all.

@phildawes: There's no pressing need for that, but IMO it'd be good to update the crates.io version some time, since it's still at 0.0.1.

**Comment by phildawes** [comment]
Cool, thanks @vadimcn

**Comment by White-Oak** [comment]
It would be better to rename issue, adressing paths in quotes, since it is not only Windows problem.
